/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.alfsamser.Paneles;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseWheelEvent;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Sergio
 */
public class PanelInferior extends javax.swing.JPanel {

    /**
     * Creates new form PanelInferiorPrueba
     */
    public PanelInferior() {
        initComponents();
    }
    
    private void actualizarLabbel() {
        jBValorZoom.setText(Integer.toString(jSZoom.getValue()) + "%");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btgDiseño = new javax.swing.ButtonGroup();
        jBPagina = new javax.swing.JButton();
        jBPalabras = new javax.swing.JButton();
        jBRevisarOrtografia = new javax.swing.JButton();
        jEspacio = new javax.swing.JLabel();
        jTBModoDeLectura = new javax.swing.JToggleButton();
        jTBDiseñoDeImpresion = new javax.swing.JToggleButton();
        jTBDiseñoWeb = new javax.swing.JToggleButton();
        jBValorZoom = new javax.swing.JButton();
        jSZoom = new javax.swing.JSlider();
        jBReducirZoom = new javax.swing.JButton();
        jBAumentarZoom = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jBPagina.setBackground(new java.awt.Color(242, 242, 242));
        jBPagina.setText("Página 1 de 1");
        jBPagina.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        add(jBPagina, gridBagConstraints);

        jBPalabras.setBackground(new java.awt.Color(242, 242, 242));
        jBPalabras.setText("10 palabras");
        jBPalabras.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        add(jBPalabras, gridBagConstraints);

        jBRevisarOrtografia.setBackground(new java.awt.Color(242, 242, 242));
        jBRevisarOrtografia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BarraInferior/revision tick (1).png"))); // NOI18N
        jBRevisarOrtografia.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        add(jBRevisarOrtografia, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        add(jEspacio, gridBagConstraints);

        jTBModoDeLectura.setBackground(new java.awt.Color(242, 242, 242));
        btgDiseño.add(jTBModoDeLectura);
        jTBModoDeLectura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BarraInferior/lectura abajo (1).png"))); // NOI18N
        jTBModoDeLectura.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        add(jTBModoDeLectura, gridBagConstraints);

        jTBDiseñoDeImpresion.setBackground(new java.awt.Color(242, 242, 242));
        btgDiseño.add(jTBDiseñoDeImpresion);
        jTBDiseñoDeImpresion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BarraInferior/diseño impresion abajo (1).png"))); // NOI18N
        jTBDiseñoDeImpresion.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        add(jTBDiseñoDeImpresion, gridBagConstraints);

        jTBDiseñoWeb.setBackground(new java.awt.Color(242, 242, 242));
        btgDiseño.add(jTBDiseñoWeb);
        jTBDiseñoWeb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BarraInferior/diseño web abajo (1) (1).png"))); // NOI18N
        jTBDiseñoWeb.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        add(jTBDiseñoWeb, gridBagConstraints);

        jBValorZoom.setBackground(new java.awt.Color(242, 242, 242));
        jBValorZoom.setText("100%");
        jBValorZoom.setBorderPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        add(jBValorZoom, gridBagConstraints);

        jSZoom.setMajorTickSpacing(10);
        jSZoom.setMaximum(500);
        jSZoom.setMinimum(10);
        jSZoom.setMinorTickSpacing(10);
        jSZoom.setValue(100);
        jSZoom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSZoom.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSZoomStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        add(jSZoom, gridBagConstraints);

        jBReducirZoom.setBackground(new java.awt.Color(242, 242, 242));
        jBReducirZoom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBReducirZoom.setForeground(new java.awt.Color(100, 100, 100));
        jBReducirZoom.setText("-");
        jBReducirZoom.setBorder(null);
        jBReducirZoom.setBorderPainted(false);
        jBReducirZoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReducirZoomActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        add(jBReducirZoom, gridBagConstraints);

        jBAumentarZoom.setBackground(new java.awt.Color(242, 242, 242));
        jBAumentarZoom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBAumentarZoom.setForeground(new java.awt.Color(100, 100, 100));
        jBAumentarZoom.setText("+");
        jBAumentarZoom.setBorder(null);
        jBAumentarZoom.setBorderPainted(false);
        jBAumentarZoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAumentarZoomActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        add(jBAumentarZoom, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jBReducirZoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReducirZoomActionPerformed
        // TODO add your handling code here:
        jSZoom.setValue(jSZoom.getValue() - 10);
        actualizarLabbel();
        
    }//GEN-LAST:event_jBReducirZoomActionPerformed

    private void jBAumentarZoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAumentarZoomActionPerformed
        // TODO add your handling code here:
        jSZoom.setValue(jSZoom.getValue() + 10);
        actualizarLabbel();
    }//GEN-LAST:event_jBAumentarZoomActionPerformed

    private void jSZoomStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSZoomStateChanged
        // TODO add your handling code here:
        actualizarLabbel();
    }//GEN-LAST:event_jSZoomStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgDiseño;
    private javax.swing.JButton jBAumentarZoom;
    private javax.swing.JButton jBPagina;
    private javax.swing.JButton jBPalabras;
    private javax.swing.JButton jBReducirZoom;
    private javax.swing.JButton jBRevisarOrtografia;
    private javax.swing.JButton jBValorZoom;
    private javax.swing.JLabel jEspacio;
    private javax.swing.JSlider jSZoom;
    private javax.swing.JToggleButton jTBDiseñoDeImpresion;
    private javax.swing.JToggleButton jTBDiseñoWeb;
    private javax.swing.JToggleButton jTBModoDeLectura;
    // End of variables declaration//GEN-END:variables
}
