/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.alfsamser.Paneles;

import java.awt.Font;

/**
 *
 * @author Alfre
 */
public class PanelSuperior extends javax.swing.JPanel {

    /**
     * Creates new form Carta
     */
    public PanelSuperior() {
        initComponents();
    }

    public Font actualizarFuente() {
        return this.panelFuente1.actulizarFuente();
    }

    public void actualizarZoom(int nuevoValor) {
        this.planelZoom1.actualizarZoom(nuevoValor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        lArchivo = new javax.swing.JLabel();
        pHome = new javax.swing.JPanel();
        panelPortapapeles1 = new es.alfsamser.Paneles.Inicio.PanelPortapapeles();
        jSeparator1 = new javax.swing.JSeparator();
        panelFuente1 = new es.alfsamser.Paneles.Inicio.PanelFuente();
        jSeparator2 = new javax.swing.JSeparator();
        panelParrafo2 = new es.alfsamser.Paneles.Inicio.PanelParrafo();
        jSeparator10 = new javax.swing.JSeparator();
        panelEstilos1 = new es.alfsamser.Paneles.Inicio.PanelEstilos();
        jSeparator3 = new javax.swing.JSeparator();
        panelEditar1 = new es.alfsamser.Paneles.Inicio.PanelEditar();
        lInsertar = new javax.swing.JLabel();
        lDiseño = new javax.swing.JLabel();
        lDisposicion = new javax.swing.JLabel();
        lReferencias = new javax.swing.JLabel();
        lCorrespondencias = new javax.swing.JLabel();
        lRevisar = new javax.swing.JLabel();
        pVista = new javax.swing.JPanel();
        panelVistas1 = new es.alfsamser.Paneles.Vista.PanelVistas();
        jSeparator4 = new javax.swing.JSeparator();
        panelMovimientoPagina2 = new es.alfsamser.Paneles.Vista.PanelMovimientoPagina();
        jSeparator5 = new javax.swing.JSeparator();
        panelMostrar1 = new es.alfsamser.Paneles.Vista.PanelMostrar();
        jSeparator6 = new javax.swing.JSeparator();
        planelZoom1 = new es.alfsamser.Paneles.Vista.PlanelZoom();
        jSeparator7 = new javax.swing.JSeparator();
        panelModoOscuro1 = new es.alfsamser.Paneles.Vista.PanelModoOscuro();
        jSeparator8 = new javax.swing.JSeparator();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.setBackground(new java.awt.Color(55, 122, 190));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));

        lArchivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lArchivo.setText("Archivo");
        jTabbedPane1.addTab("Archivo", lArchivo);

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0);
        flowLayout1.setAlignOnBaseline(true);
        pHome.setLayout(flowLayout1);

        panelPortapapeles1.setMinimumSize(new java.awt.Dimension(158, 90));
        panelPortapapeles1.setPreferredSize(new java.awt.Dimension(211, 90));
        pHome.add(panelPortapapeles1);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setEnabled(false);
        jSeparator1.setMaximumSize(new java.awt.Dimension(10, 90));
        jSeparator1.setMinimumSize(new java.awt.Dimension(10, 30));
        jSeparator1.setName(""); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(10, 85));
        jSeparator1.setRequestFocusEnabled(false);
        pHome.add(jSeparator1);

        panelFuente1.setMinimumSize(new java.awt.Dimension(297, 90));
        panelFuente1.setPreferredSize(new java.awt.Dimension(320, 90));
        pHome.add(panelFuente1);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setAlignmentX(0.0F);
        jSeparator2.setEnabled(false);
        jSeparator2.setMaximumSize(new java.awt.Dimension(10, 90));
        jSeparator2.setMinimumSize(new java.awt.Dimension(10, 30));
        jSeparator2.setName(""); // NOI18N
        jSeparator2.setPreferredSize(new java.awt.Dimension(10, 85));
        jSeparator2.setRequestFocusEnabled(false);
        pHome.add(jSeparator2);

        panelParrafo2.setMinimumSize(new java.awt.Dimension(254, 90));
        panelParrafo2.setPreferredSize(new java.awt.Dimension(254, 90));
        pHome.add(panelParrafo2);

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator10.setAlignmentX(0.0F);
        jSeparator10.setEnabled(false);
        jSeparator10.setMaximumSize(new java.awt.Dimension(10, 90));
        jSeparator10.setMinimumSize(new java.awt.Dimension(10, 30));
        jSeparator10.setName(""); // NOI18N
        jSeparator10.setPreferredSize(new java.awt.Dimension(10, 85));
        jSeparator10.setRequestFocusEnabled(false);
        pHome.add(jSeparator10);

        panelEstilos1.setPreferredSize(new java.awt.Dimension(600, 90));
        pHome.add(panelEstilos1);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setEnabled(false);
        jSeparator3.setMaximumSize(new java.awt.Dimension(10, 90));
        jSeparator3.setMinimumSize(new java.awt.Dimension(10, 30));
        jSeparator3.setName(""); // NOI18N
        jSeparator3.setPreferredSize(new java.awt.Dimension(10, 85));
        jSeparator3.setRequestFocusEnabled(false);
        pHome.add(jSeparator3);

        panelEditar1.setMaximumSize(new java.awt.Dimension(150, 90));
        panelEditar1.setMinimumSize(new java.awt.Dimension(150, 90));
        panelEditar1.setPreferredSize(new java.awt.Dimension(100, 90));
        pHome.add(panelEditar1);

        jTabbedPane1.addTab("Inicio", pHome);

        lInsertar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lInsertar.setText("Insertar");
        jTabbedPane1.addTab("Insertar", lInsertar);

        lDiseño.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lDiseño.setText("Diseño");
        jTabbedPane1.addTab("Diseño", lDiseño);

        lDisposicion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lDisposicion.setText("Disposición");
        jTabbedPane1.addTab("Disposición", lDisposicion);

        lReferencias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lReferencias.setText("Referencias");
        lReferencias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jTabbedPane1.addTab("Referencias", lReferencias);

        lCorrespondencias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCorrespondencias.setText("Correspondencias");
        jTabbedPane1.addTab("Correspondecias", lCorrespondencias);

        lRevisar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lRevisar.setText("Revisar");
        jTabbedPane1.addTab("Revisar", lRevisar);

        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0);
        flowLayout2.setAlignOnBaseline(true);
        pVista.setLayout(flowLayout2);
        pVista.add(panelVistas1);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setEnabled(false);
        jSeparator4.setMaximumSize(new java.awt.Dimension(10, 90));
        jSeparator4.setMinimumSize(new java.awt.Dimension(10, 30));
        jSeparator4.setName(""); // NOI18N
        jSeparator4.setPreferredSize(new java.awt.Dimension(10, 85));
        jSeparator4.setRequestFocusEnabled(false);
        pVista.add(jSeparator4);

        panelMovimientoPagina2.setMaximumSize(new java.awt.Dimension(125, 90));
        panelMovimientoPagina2.setMinimumSize(new java.awt.Dimension(125, 90));
        panelMovimientoPagina2.setPreferredSize(new java.awt.Dimension(125, 90));
        pVista.add(panelMovimientoPagina2);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setEnabled(false);
        jSeparator5.setMaximumSize(new java.awt.Dimension(10, 90));
        jSeparator5.setMinimumSize(new java.awt.Dimension(10, 30));
        jSeparator5.setName(""); // NOI18N
        jSeparator5.setPreferredSize(new java.awt.Dimension(10, 85));
        jSeparator5.setRequestFocusEnabled(false);
        pVista.add(jSeparator5);

        panelMostrar1.setPreferredSize(new java.awt.Dimension(140, 90));
        pVista.add(panelMostrar1);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator6.setEnabled(false);
        jSeparator6.setMaximumSize(new java.awt.Dimension(10, 90));
        jSeparator6.setMinimumSize(new java.awt.Dimension(10, 30));
        jSeparator6.setName(""); // NOI18N
        jSeparator6.setPreferredSize(new java.awt.Dimension(10, 85));
        jSeparator6.setRequestFocusEnabled(false);
        pVista.add(jSeparator6);

        planelZoom1.setPreferredSize(new java.awt.Dimension(122, 92));
        pVista.add(planelZoom1);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator7.setEnabled(false);
        jSeparator7.setMaximumSize(new java.awt.Dimension(10, 90));
        jSeparator7.setMinimumSize(new java.awt.Dimension(10, 30));
        jSeparator7.setName(""); // NOI18N
        jSeparator7.setPreferredSize(new java.awt.Dimension(10, 85));
        jSeparator7.setRequestFocusEnabled(false);
        pVista.add(jSeparator7);

        panelModoOscuro1.setPreferredSize(new java.awt.Dimension(80, 90));
        pVista.add(panelModoOscuro1);

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator8.setEnabled(false);
        jSeparator8.setMaximumSize(new java.awt.Dimension(10, 90));
        jSeparator8.setMinimumSize(new java.awt.Dimension(10, 30));
        jSeparator8.setName(""); // NOI18N
        jSeparator8.setPreferredSize(new java.awt.Dimension(10, 85));
        jSeparator8.setRequestFocusEnabled(false);
        pVista.add(jSeparator8);

        jTabbedPane1.addTab("Vista", pVista);

        jTabbedPane1.setSelectedIndex(1);

        add(jTabbedPane1);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lArchivo;
    private javax.swing.JLabel lCorrespondencias;
    private javax.swing.JLabel lDiseño;
    private javax.swing.JLabel lDisposicion;
    private javax.swing.JLabel lInsertar;
    private javax.swing.JLabel lReferencias;
    private javax.swing.JLabel lRevisar;
    private javax.swing.JPanel pHome;
    private javax.swing.JPanel pVista;
    private es.alfsamser.Paneles.Inicio.PanelEditar panelEditar1;
    private es.alfsamser.Paneles.Inicio.PanelEstilos panelEstilos1;
    private es.alfsamser.Paneles.Inicio.PanelFuente panelFuente1;
    private es.alfsamser.Paneles.Vista.PanelModoOscuro panelModoOscuro1;
    private es.alfsamser.Paneles.Vista.PanelMostrar panelMostrar1;
    private es.alfsamser.Paneles.Vista.PanelMovimientoPagina panelMovimientoPagina2;
    private es.alfsamser.Paneles.Inicio.PanelParrafo panelParrafo2;
    private es.alfsamser.Paneles.Inicio.PanelPortapapeles panelPortapapeles1;
    private es.alfsamser.Paneles.Vista.PanelVistas panelVistas1;
    private es.alfsamser.Paneles.Vista.PlanelZoom planelZoom1;
    // End of variables declaration//GEN-END:variables
}
