/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.alfsamser.Plantillas;

/**
 *
 * @author Alfre
 */
public class BarraTitulo extends javax.swing.JPanel {

    /**
     * Creates new form BarraTitulo
     */
    public BarraTitulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bGuardar = new javax.swing.JButton();
        bDeshacer = new javax.swing.JButton();
        bRehacer = new javax.swing.JButton();
        bNose = new javax.swing.JButton();
        lNombreDocumento = new javax.swing.JLabel();
        bNose2 = new javax.swing.JButton();
        bMinimizar = new javax.swing.JButton();
        bMaximizar = new javax.swing.JButton();
        bCerrar = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        bGuardar.setBackground(new java.awt.Color(242, 242, 242));
        bGuardar.setText("guardar");
        bGuardar.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(bGuardar, gridBagConstraints);

        bDeshacer.setBackground(new java.awt.Color(242, 242, 242));
        bDeshacer.setText("D");
        bDeshacer.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(bDeshacer, gridBagConstraints);

        bRehacer.setBackground(new java.awt.Color(242, 242, 242));
        bRehacer.setText("R");
        bRehacer.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(bRehacer, gridBagConstraints);

        bNose.setBackground(new java.awt.Color(242, 242, 242));
        bNose.setText("🞃");
        bNose.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(bNose, gridBagConstraints);

        lNombreDocumento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lNombreDocumento.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        add(lNombreDocumento, gridBagConstraints);

        bNose2.setBackground(new java.awt.Color(242, 242, 242));
        bNose2.setText("A");
        bNose2.setBorder(null);
        bNose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNose2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(bNose2, gridBagConstraints);

        bMinimizar.setBackground(new java.awt.Color(242, 242, 242));
        bMinimizar.setText("A");
        bMinimizar.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(bMinimizar, gridBagConstraints);

        bMaximizar.setBackground(new java.awt.Color(242, 242, 242));
        bMaximizar.setText("A");
        bMaximizar.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(bMaximizar, gridBagConstraints);

        bCerrar.setBackground(new java.awt.Color(242, 242, 242));
        bCerrar.setText("A");
        bCerrar.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(bCerrar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void bNose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNose2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bNose2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCerrar;
    private javax.swing.JButton bDeshacer;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bMaximizar;
    private javax.swing.JButton bMinimizar;
    private javax.swing.JButton bNose;
    private javax.swing.JButton bNose2;
    private javax.swing.JButton bRehacer;
    private javax.swing.JLabel lNombreDocumento;
    // End of variables declaration//GEN-END:variables
}
