/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.alfsamser.Plantillas;

/**
 *
 * @author Samu
 */
public class PanelMovimientoPagina extends javax.swing.JPanel {

    /**
     * Creates new form Plantilla
     */
    public PanelMovimientoPagina() {
        initComponents();
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contenido = new javax.swing.JPanel();
        bVertical = new javax.swing.JButton();
        bParalelo = new javax.swing.JButton();
        etiquetaInferior = new javax.swing.JPanel();
        etiqueta = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        contenido.setBackground(new java.awt.Color(243, 243, 243));
        contenido.setLayout(new java.awt.GridLayout(1, 0));

        bVertical.setBackground(new java.awt.Color(243, 243, 243));
        bVertical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vista/Vertical.png"))); // NOI18N
        bVertical.setText("Vertical");
        bVertical.setBorder(null);
        bVertical.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bVertical.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bVertical.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        contenido.add(bVertical);

        bParalelo.setBackground(new java.awt.Color(243, 243, 243));
        bParalelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vista/Paralelo.png"))); // NOI18N
        bParalelo.setText("En paralelo");
        bParalelo.setBorder(null);
        bParalelo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bParalelo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bParalelo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        contenido.add(bParalelo);

        add(contenido, java.awt.BorderLayout.CENTER);

        etiquetaInferior.setLayout(new java.awt.GridBagLayout());

        etiqueta.setForeground(new java.awt.Color(112, 108, 108));
        etiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta.setText("Movimiento de página");
        etiqueta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        etiqueta.setFocusable(false);
        etiqueta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        etiqueta.setPreferredSize(new java.awt.Dimension(200, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BELOW_BASELINE;
        gridBagConstraints.weightx = 1.0;
        etiquetaInferior.add(etiqueta, gridBagConstraints);

        add(etiquetaInferior, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bParalelo;
    private javax.swing.JButton bVertical;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel etiqueta;
    private javax.swing.JPanel etiquetaInferior;
    // End of variables declaration//GEN-END:variables
}
