/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.alfsamser.Paneles.Inicio;

/**
 *
 * @author Alfre
 */
public class PanelPortapapeles extends javax.swing.JPanel {

    /**
     * Creates new form Plantilla
     */
    public PanelPortapapeles() {
        initComponents();
        bIcono.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contenido = new javax.swing.JPanel();
        bPegar = new javax.swing.JButton();
        bCortar = new javax.swing.JButton();
        bCopiar = new javax.swing.JButton();
        bCopiarFormato = new javax.swing.JButton();
        etiquetaInferior = new javax.swing.JPanel();
        etiqueta = new javax.swing.JLabel();
        bIcono = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        contenido.setBackground(new java.awt.Color(241, 241, 241));
        contenido.setOpaque(false);
        contenido.setLayout(new java.awt.GridBagLayout());

        bPegar.setBackground(new java.awt.Color(241, 241, 241));
        bPegar.setForeground(new java.awt.Color(112, 108, 108));
        bPegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Portapapeles/Pegar36x36.png"))); // NOI18N
        bPegar.setText("Pegar");
        bPegar.setBorder(null);
        bPegar.setEnabled(false);
        bPegar.setHideActionText(true);
        bPegar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bPegar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        contenido.add(bPegar, gridBagConstraints);

        bCortar.setBackground(new java.awt.Color(241, 241, 241));
        bCortar.setForeground(new java.awt.Color(112, 108, 108));
        bCortar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Portapapeles/cortar18x18.png"))); // NOI18N
        bCortar.setText("Cortar");
        bCortar.setBorder(null);
        bCortar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bCortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCortarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenido.add(bCortar, gridBagConstraints);

        bCopiar.setBackground(new java.awt.Color(241, 241, 241));
        bCopiar.setForeground(new java.awt.Color(112, 108, 108));
        bCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Portapapeles/copiar18x18.png"))); // NOI18N
        bCopiar.setText("Copiar");
        bCopiar.setBorder(null);
        bCopiar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bCopiar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCopiarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenido.add(bCopiar, gridBagConstraints);

        bCopiarFormato.setBackground(new java.awt.Color(241, 241, 241));
        bCopiarFormato.setForeground(new java.awt.Color(112, 108, 108));
        bCopiarFormato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Portapapeles/copiarFormato18x18.png"))); // NOI18N
        bCopiarFormato.setText("Copiar formato");
        bCopiarFormato.setBorder(null);
        bCopiarFormato.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenido.add(bCopiarFormato, gridBagConstraints);

        add(contenido, java.awt.BorderLayout.CENTER);

        etiquetaInferior.setBackground(new java.awt.Color(241, 241, 241));
        etiquetaInferior.setOpaque(false);
        etiquetaInferior.setLayout(new java.awt.GridBagLayout());

        etiqueta.setBackground(new java.awt.Color(241, 241, 241));
        etiqueta.setForeground(new java.awt.Color(112, 108, 108));
        etiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta.setText("Portapapeles");
        etiqueta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        etiqueta.setFocusable(false);
        etiqueta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        etiqueta.setOpaque(true);
        etiqueta.setPreferredSize(new java.awt.Dimension(200, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BELOW_BASELINE;
        gridBagConstraints.weightx = 1.0;
        etiquetaInferior.add(etiqueta, gridBagConstraints);

        bIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flechaInferiorIzq8.png"))); // NOI18N
        bIcono.setBorder(null);
        bIcono.setContentAreaFilled(false);
        bIcono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bIcono.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BELOW_BASELINE;
        etiquetaInferior.add(bIcono, gridBagConstraints);

        add(etiquetaInferior, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void bCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCopiarActionPerformed
        bPegar.setEnabled(true);
    }//GEN-LAST:event_bCopiarActionPerformed

    private void bCortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCortarActionPerformed
        bPegar.setEnabled(true);
    }//GEN-LAST:event_bCortarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCopiar;
    private javax.swing.JButton bCopiarFormato;
    private javax.swing.JButton bCortar;
    private javax.swing.JButton bIcono;
    private javax.swing.JButton bPegar;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel etiqueta;
    private javax.swing.JPanel etiquetaInferior;
    // End of variables declaration//GEN-END:variables
}
