/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.alfsamser.Paneles.Inicio;

/**
 *
 * @author Samu
 */
public class PanelEdición extends javax.swing.JPanel {

    /**
     * Creates new form Plantilla
     */
    public PanelEdición() {
        initComponents();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contenido = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bBuscar = new javax.swing.JButton();
        bBuscarFlecha = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bReemplazar = new javax.swing.JButton();
        bSeleccionar = new javax.swing.JButton();
        etiquetaInferior = new javax.swing.JPanel();
        etiqueta = new javax.swing.JLabel();

        setBackground(new java.awt.Color(243, 243, 243));
        setPreferredSize(new java.awt.Dimension(150, 100));
        setLayout(new java.awt.BorderLayout());

        contenido.setBackground(new java.awt.Color(243, 243, 243));
        contenido.setAlignmentX(0.0F);
        contenido.setAlignmentY(0.0F);
        contenido.setMinimumSize(new java.awt.Dimension(110, 29));
        contenido.setPreferredSize(new java.awt.Dimension(150, 100));
        contenido.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(243, 243, 243));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        bBuscar.setBackground(new java.awt.Color(243, 243, 243));
        bBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Editar/buscar (1).png"))); // NOI18N
        bBuscar.setText("Buscar");
        bBuscar.setAlignmentY(0.0F);
        bBuscar.setBorder(null);
        bBuscar.setBorderPainted(false);
        bBuscar.setMaximumSize(new java.awt.Dimension(100, 30));
        bBuscar.setMinimumSize(new java.awt.Dimension(100, 30));
        jPanel1.add(bBuscar);

        bBuscarFlecha.setBackground(new java.awt.Color(243, 243, 243));
        bBuscarFlecha.setText("🞃");
        bBuscarFlecha.setAlignmentY(0.0F);
        bBuscarFlecha.setBorder(null);
        bBuscarFlecha.setBorderPainted(false);
        jPanel1.add(bBuscarFlecha);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        contenido.add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        bReemplazar.setBackground(new java.awt.Color(243, 243, 243));
        bReemplazar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Editar/reemplazarW.png"))); // NOI18N
        bReemplazar.setText("Reemplazar    ");
        bReemplazar.setBorder(null);
        bReemplazar.setBorderPainted(false);
        bReemplazar.setMaximumSize(new java.awt.Dimension(150, 30));
        bReemplazar.setMinimumSize(new java.awt.Dimension(150, 30));
        jPanel2.add(bReemplazar);

        bSeleccionar.setBackground(new java.awt.Color(243, 243, 243));
        bSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Editar/seleccionar (1).png"))); // NOI18N
        bSeleccionar.setText("Seleccionar 🞃");
        bSeleccionar.setBorder(null);
        bSeleccionar.setBorderPainted(false);
        bSeleccionar.setMaximumSize(new java.awt.Dimension(150, 30));
        bSeleccionar.setMinimumSize(new java.awt.Dimension(150, 30));
        jPanel2.add(bSeleccionar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        contenido.add(jPanel2, gridBagConstraints);

        add(contenido, java.awt.BorderLayout.CENTER);

        etiquetaInferior.setLayout(new java.awt.GridBagLayout());

        etiqueta.setForeground(new java.awt.Color(112, 108, 108));
        etiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta.setText("Edición");
        etiqueta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        etiqueta.setFocusable(false);
        etiqueta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        etiqueta.setPreferredSize(new java.awt.Dimension(1500, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BELOW_BASELINE;
        gridBagConstraints.weightx = 1.0;
        etiquetaInferior.add(etiqueta, gridBagConstraints);

        add(etiquetaInferior, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bBuscarFlecha;
    private javax.swing.JButton bReemplazar;
    private javax.swing.JButton bSeleccionar;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel etiqueta;
    private javax.swing.JPanel etiquetaInferior;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
