/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.alfsamser.Paneles.Inicio;

/**
 *
 * @author Samu
 */
public class PanelEditar extends javax.swing.JPanel {

    /**
     * Creates new form Plantilla
     */
    public PanelEditar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contenido = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bBuscar = new javax.swing.JButton();
        bBuscarFlecha = new javax.swing.JButton();
        bReemplazar = new javax.swing.JButton();
        bSeleccionar = new javax.swing.JButton();
        etiquetaInferior = new javax.swing.JPanel();
        etiqueta = new javax.swing.JLabel();

        setBackground(new java.awt.Color(243, 243, 243));
        setMaximumSize(new java.awt.Dimension(93, 90));
        setMinimumSize(new java.awt.Dimension(93, 90));
        setPreferredSize(new java.awt.Dimension(93, 90));
        setLayout(new java.awt.BorderLayout());

        contenido.setBackground(new java.awt.Color(243, 243, 243));
        contenido.setAlignmentX(0.0F);
        contenido.setAlignmentY(0.0F);
        contenido.setMaximumSize(new java.awt.Dimension(92, 75));
        contenido.setMinimumSize(new java.awt.Dimension(92, 75));
        contenido.setPreferredSize(new java.awt.Dimension(92, 75));
        contenido.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jPanel1.setMaximumSize(new java.awt.Dimension(73, 29));
        jPanel1.setMinimumSize(new java.awt.Dimension(73, 29));
        jPanel1.setPreferredSize(new java.awt.Dimension(73, 29));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        bBuscar.setBackground(new java.awt.Color(243, 243, 243));
        bBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Editar/buscar (1).png"))); // NOI18N
        bBuscar.setText("Buscar");
        bBuscar.setAlignmentY(0.0F);
        bBuscar.setBorder(null);
        bBuscar.setBorderPainted(false);
        jPanel1.add(bBuscar);

        bBuscarFlecha.setBackground(new java.awt.Color(243, 243, 243));
        bBuscarFlecha.setText("🞃");
        bBuscarFlecha.setAlignmentY(0.0F);
        bBuscarFlecha.setBorder(null);
        bBuscarFlecha.setBorderPainted(false);
        bBuscarFlecha.setMaximumSize(new java.awt.Dimension(16, 18));
        bBuscarFlecha.setMinimumSize(new java.awt.Dimension(16, 18));
        bBuscarFlecha.setPreferredSize(new java.awt.Dimension(16, 18));
        jPanel1.add(bBuscarFlecha);

        contenido.add(jPanel1);

        bReemplazar.setBackground(new java.awt.Color(243, 243, 243));
        bReemplazar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Editar/reemplazarW.png"))); // NOI18N
        bReemplazar.setText("Reemplazar    ");
        bReemplazar.setBorder(null);
        bReemplazar.setBorderPainted(false);
        bReemplazar.setMaximumSize(new java.awt.Dimension(95, 28));
        bReemplazar.setMinimumSize(new java.awt.Dimension(95, 28));
        bReemplazar.setPreferredSize(new java.awt.Dimension(95, 25));
        contenido.add(bReemplazar);

        bSeleccionar.setBackground(new java.awt.Color(243, 243, 243));
        bSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Editar/seleccionar (1).png"))); // NOI18N
        bSeleccionar.setText("Seleccionar 🞃");
        bSeleccionar.setBorder(null);
        bSeleccionar.setBorderPainted(false);
        bSeleccionar.setMaximumSize(new java.awt.Dimension(90, 28));
        bSeleccionar.setMinimumSize(new java.awt.Dimension(90, 28));
        bSeleccionar.setPreferredSize(new java.awt.Dimension(90, 25));
        contenido.add(bSeleccionar);

        add(contenido, java.awt.BorderLayout.CENTER);

        etiquetaInferior.setLayout(new java.awt.GridBagLayout());

        etiqueta.setForeground(new java.awt.Color(112, 108, 108));
        etiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta.setText("Editar");
        etiqueta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        etiqueta.setFocusable(false);
        etiqueta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        etiqueta.setPreferredSize(new java.awt.Dimension(1500, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BELOW_BASELINE;
        gridBagConstraints.weightx = 1.0;
        etiquetaInferior.add(etiqueta, gridBagConstraints);

        add(etiquetaInferior, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bBuscarFlecha;
    private javax.swing.JButton bReemplazar;
    private javax.swing.JButton bSeleccionar;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel etiqueta;
    private javax.swing.JPanel etiquetaInferior;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
