/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.alfsamser.Paneles.Vista;

/**
 *
 * @author Samu
 */
public class PanelModoOscuro extends javax.swing.JPanel {

    /**
     * Creates new form Plantilla
     */
    public PanelModoOscuro() {
        initComponents();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contenido = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        etiquetaInferior = new javax.swing.JPanel();
        etiqueta = new javax.swing.JLabel();

        setBackground(new java.awt.Color(243, 243, 243));
        setMinimumSize(new java.awt.Dimension(70, 50));
        setPreferredSize(new java.awt.Dimension(70, 100));
        setLayout(new java.awt.BorderLayout());

        contenido.setBackground(new java.awt.Color(243, 243, 243));
        contenido.setAlignmentX(0.0F);
        contenido.setAlignmentY(0.0F);
        contenido.setMinimumSize(new java.awt.Dimension(50, 29));
        contenido.setPreferredSize(new java.awt.Dimension(50, 100));
        contenido.setLayout(new javax.swing.BoxLayout(contenido, javax.swing.BoxLayout.LINE_AXIS));

        jToggleButton1.setBackground(new java.awt.Color(243, 243, 243));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vista/ModoOscuro.png"))); // NOI18N
        jToggleButton1.setText("<html><p>Modo</p><p>oscuro</p></html>");
        jToggleButton1.setBorder(null);
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        contenido.add(jToggleButton1);

        add(contenido, java.awt.BorderLayout.CENTER);

        etiquetaInferior.setLayout(new java.awt.GridBagLayout());

        etiqueta.setForeground(new java.awt.Color(112, 108, 108));
        etiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta.setText("Modo Oscuro");
        etiqueta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        etiqueta.setFocusable(false);
        etiqueta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        etiqueta.setMaximumSize(new java.awt.Dimension(70, 21));
        etiqueta.setMinimumSize(new java.awt.Dimension(70, 21));
        etiqueta.setPreferredSize(new java.awt.Dimension(70, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BELOW_BASELINE;
        gridBagConstraints.weightx = 1.0;
        etiquetaInferior.add(etiqueta, gridBagConstraints);

        add(etiquetaInferior, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel etiqueta;
    private javax.swing.JPanel etiquetaInferior;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
