/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.alfsamser.Paneles.Vista;

/**
 *
 * @author Samu
 */
public class PanelMovimientoPagina extends javax.swing.JPanel {

    /**
     * Creates new form Plantilla
     */
    public PanelMovimientoPagina() {
        initComponents();
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgMovimientoPagina = new javax.swing.ButtonGroup();
        contenido = new javax.swing.JPanel();
        tbEditar = new javax.swing.JToggleButton();
        tbParalelo = new javax.swing.JToggleButton();
        etiquetaInferior = new javax.swing.JPanel();
        etiqueta = new javax.swing.JLabel();

        setBackground(new java.awt.Color(243, 243, 243));
        setLayout(new java.awt.BorderLayout());

        contenido.setBackground(new java.awt.Color(243, 243, 243));
        contenido.setMaximumSize(new java.awt.Dimension(57, 57));
        contenido.setLayout(new java.awt.GridLayout(1, 0));

        tbEditar.setBackground(new java.awt.Color(243, 243, 243));
        tbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vista/Vertical.png"))); // NOI18N
        tbEditar.setText("Vertical");
        tbEditar.setBorder(null);
        tbEditar.setBorderPainted(false);
        tbEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbEditar.setMargin(new java.awt.Insets(14, 14, 2, 14));
        tbEditar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        tbEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbEditarActionPerformed(evt);
            }
        });
        contenido.add(tbEditar);

        tbParalelo.setBackground(new java.awt.Color(243, 243, 243));
        bgMovimientoPagina.add(tbParalelo);
        tbParalelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vista/Paralelo.png"))); // NOI18N
        tbParalelo.setText("<html><p1 align=\"center\"><p>En</p><p>paralelo</p></p1></html>");
        tbParalelo.setBorder(null);
        tbParalelo.setBorderPainted(false);
        tbParalelo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbParalelo.setMargin(new java.awt.Insets(14, 14, 2, 14));
        tbParalelo.setMaximumSize(new java.awt.Dimension(60, 80));
        tbParalelo.setMinimumSize(new java.awt.Dimension(50, 57));
        tbParalelo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        tbParalelo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbParalelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbParaleloActionPerformed(evt);
            }
        });
        contenido.add(tbParalelo);

        add(contenido, java.awt.BorderLayout.CENTER);

        etiqueta.setForeground(new java.awt.Color(112, 108, 108));
        etiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta.setText("Movimiento de página");
        etiqueta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        etiqueta.setFocusable(false);
        etiqueta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        etiqueta.setPreferredSize(new java.awt.Dimension(200, 15));

        javax.swing.GroupLayout etiquetaInferiorLayout = new javax.swing.GroupLayout(etiquetaInferior);
        etiquetaInferior.setLayout(etiquetaInferiorLayout);
        etiquetaInferiorLayout.setHorizontalGroup(
            etiquetaInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        etiquetaInferiorLayout.setVerticalGroup(
            etiquetaInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        add(etiquetaInferior, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void tbParaleloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbParaleloActionPerformed
     this.tbEditar.setSelected(false);
    }//GEN-LAST:event_tbParaleloActionPerformed

    private void tbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbEditarActionPerformed
    this.tbParalelo.setSelected(false);
    }//GEN-LAST:event_tbEditarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgMovimientoPagina;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel etiqueta;
    private javax.swing.JPanel etiquetaInferior;
    private javax.swing.JToggleButton tbEditar;
    private javax.swing.JToggleButton tbParalelo;
    // End of variables declaration//GEN-END:variables
}
