/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.alfsamser.Paneles.Vista;

/**
 *
 * @author Samu
 */
public class PanelMovimientoPagina extends javax.swing.JPanel {

    /**
     * Creates new form Plantilla
     */
    public PanelMovimientoPagina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgMovimientoPagina = new javax.swing.ButtonGroup();
        contenido = new javax.swing.JPanel();
        tbVertical = new javax.swing.JToggleButton();
        tbParalelo = new javax.swing.JToggleButton();
        etiqueta = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        contenido.setBackground(new java.awt.Color(243, 243, 243));
        contenido.setMaximumSize(new java.awt.Dimension(57, 57));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 3);
        flowLayout1.setAlignOnBaseline(true);
        contenido.setLayout(flowLayout1);

        tbVertical.setBackground(new java.awt.Color(243, 243, 243));
        bgMovimientoPagina.add(tbVertical);
        tbVertical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vista/Vertical.png"))); // NOI18N
        tbVertical.setText("<html><p1 align=\"center\"><p>Vertical</p></p1></html>");
        tbVertical.setAlignmentY(1.0F);
        tbVertical.setBorder(null);
        tbVertical.setBorderPainted(false);
        tbVertical.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbVertical.setMargin(new java.awt.Insets(14, 0, 0, 0));
        tbVertical.setMaximumSize(new java.awt.Dimension(60, 80));
        tbVertical.setMinimumSize(new java.awt.Dimension(50, 57));
        tbVertical.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        tbVertical.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        contenido.add(tbVertical);

        tbParalelo.setBackground(new java.awt.Color(243, 243, 243));
        bgMovimientoPagina.add(tbParalelo);
        tbParalelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vista/Paralelo.png"))); // NOI18N
        tbParalelo.setText("<html><p1 align=\"center\"><p>En</p><p>paralelo</p></p1></html>");
        tbParalelo.setBorder(null);
        tbParalelo.setBorderPainted(false);
        tbParalelo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbParalelo.setMargin(new java.awt.Insets(14, 14, 2, 14));
        tbParalelo.setMaximumSize(new java.awt.Dimension(60, 80));
        tbParalelo.setMinimumSize(new java.awt.Dimension(50, 57));
        tbParalelo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        contenido.add(tbParalelo);

        add(contenido, java.awt.BorderLayout.CENTER);

        etiqueta.setForeground(new java.awt.Color(112, 108, 108));
        etiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta.setText("Movimiento de página");
        etiqueta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        etiqueta.setFocusable(false);
        etiqueta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        etiqueta.setPreferredSize(new java.awt.Dimension(200, 15));
        add(etiqueta, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgMovimientoPagina;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel etiqueta;
    private javax.swing.JToggleButton tbParalelo;
    private javax.swing.JToggleButton tbVertical;
    // End of variables declaration//GEN-END:variables
}
