/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.alfsamser.Paneles.Vista;

import es.alfsamser.Paneles.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Alfre
 */
public class PanelMostrar extends javax.swing.JPanel {

    /**
     * Creates new form Plantilla
     */
    public PanelMostrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contenido = new javax.swing.JPanel();
        checkRegla = new javax.swing.JCheckBox();
        checkGrid = new javax.swing.JCheckBox();
        checkPanel = new javax.swing.JCheckBox();
        etiqueta = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        contenido.setLayout(new java.awt.GridBagLayout());

        checkRegla.setText("Regla");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        contenido.add(checkRegla, gridBagConstraints);

        checkGrid.setText("Grid");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        contenido.add(checkGrid, gridBagConstraints);

        checkPanel.setText("Panel de Navegación");
        checkPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPanelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        contenido.add(checkPanel, gridBagConstraints);

        add(contenido, java.awt.BorderLayout.CENTER);

        etiqueta.setForeground(new java.awt.Color(112, 108, 108));
        etiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta.setText("Etiqueta");
        etiqueta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        etiqueta.setFocusable(false);
        etiqueta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        etiqueta.setPreferredSize(new java.awt.Dimension(200, 15));
        add(etiqueta, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void checkPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPanelActionPerformed
        String a = JOptionPane.showInputDialog("Panel de Navegación");
        System.out.println("" + a);
        checkPanel.setSelected(false);
    }//GEN-LAST:event_checkPanelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkGrid;
    private javax.swing.JCheckBox checkPanel;
    private javax.swing.JCheckBox checkRegla;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel etiqueta;
    // End of variables declaration//GEN-END:variables
}
