/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.alfsamser.Paneles.Vista;

/**
 *
 * @author Samu
 */
public class PanelVistas extends javax.swing.JPanel {

    /**
     * Creates new form Plantilla
     */
    public PanelVistas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bgVistas = new javax.swing.ButtonGroup();
        contenido = new javax.swing.JPanel();
        pBotonesGrandes = new javax.swing.JPanel();
        tbMLectura = new javax.swing.JToggleButton();
        tbDImpresion = new javax.swing.JToggleButton();
        tbDWeb = new javax.swing.JToggleButton();
        pBotonesPequennos = new javax.swing.JPanel();
        tbEsquema = new javax.swing.JToggleButton();
        tbBorrador = new javax.swing.JToggleButton();
        etiquetaInferior = new javax.swing.JPanel();
        etiqueta = new javax.swing.JLabel();

        setBackground(new java.awt.Color(243, 243, 243));
        setLayout(new java.awt.BorderLayout());

        contenido.setBackground(new java.awt.Color(243, 243, 243));
        contenido.setLayout(new java.awt.GridBagLayout());

        pBotonesGrandes.setBackground(new java.awt.Color(243, 243, 243));
        pBotonesGrandes.setLayout(new javax.swing.BoxLayout(pBotonesGrandes, javax.swing.BoxLayout.LINE_AXIS));

        tbMLectura.setBackground(new java.awt.Color(243, 243, 243));
        bgVistas.add(tbMLectura);
        tbMLectura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vista/LeerMas.png"))); // NOI18N
        tbMLectura.setText("<html><p1 align=\"center\"><p>Modo</p><p>Lectura</p></p1></html>");
        tbMLectura.setBorder(null);
        tbMLectura.setBorderPainted(false);
        tbMLectura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbMLectura.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tbMLectura.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pBotonesGrandes.add(tbMLectura);

        tbDImpresion.setBackground(new java.awt.Color(243, 243, 243));
        bgVistas.add(tbDImpresion);
        tbDImpresion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vista/DiseñoImpresion.png"))); // NOI18N
        tbDImpresion.setText("<html><p1 align=\"center\"><p>Diseño de</p><p>impresión</p></p1></html>");
        tbDImpresion.setBorder(null);
        tbDImpresion.setBorderPainted(false);
        tbDImpresion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbDImpresion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tbDImpresion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbDImpresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDImpresionActionPerformed(evt);
            }
        });
        pBotonesGrandes.add(tbDImpresion);

        tbDWeb.setBackground(new java.awt.Color(243, 243, 243));
        bgVistas.add(tbDWeb);
        tbDWeb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vista/DiseñoWeb.png"))); // NOI18N
        tbDWeb.setText("<html><p1 align=\"center\"><p>Diseño</p><p>web</p></p1></html>");
        tbDWeb.setBorder(null);
        tbDWeb.setBorderPainted(false);
        tbDWeb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbDWeb.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tbDWeb.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbDWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDWebActionPerformed(evt);
            }
        });
        pBotonesGrandes.add(tbDWeb);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 21;
        contenido.add(pBotonesGrandes, gridBagConstraints);

        pBotonesPequennos.setBackground(new java.awt.Color(243, 243, 243));
        pBotonesPequennos.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        tbEsquema.setBackground(new java.awt.Color(243, 243, 243));
        bgVistas.add(tbEsquema);
        tbEsquema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vista/esquema18.png"))); // NOI18N
        tbEsquema.setText("Esquema");
        tbEsquema.setBorder(null);
        tbEsquema.setBorderPainted(false);
        tbEsquema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbEsquemaActionPerformed(evt);
            }
        });
        pBotonesPequennos.add(tbEsquema);

        tbBorrador.setBackground(new java.awt.Color(243, 243, 243));
        bgVistas.add(tbBorrador);
        tbBorrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vista/borrador.png"))); // NOI18N
        tbBorrador.setText("Borrador");
        tbBorrador.setBorder(null);
        tbBorrador.setBorderPainted(false);
        tbBorrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbBorradorActionPerformed(evt);
            }
        });
        pBotonesPequennos.add(tbBorrador);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        contenido.add(pBotonesPequennos, gridBagConstraints);

        add(contenido, java.awt.BorderLayout.CENTER);

        etiquetaInferior.setLayout(new java.awt.GridBagLayout());

        etiqueta.setForeground(new java.awt.Color(112, 108, 108));
        etiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta.setText("Vistas");
        etiqueta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        etiqueta.setFocusable(false);
        etiqueta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        etiqueta.setPreferredSize(new java.awt.Dimension(200, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BELOW_BASELINE;
        gridBagConstraints.weightx = 1.0;
        etiquetaInferior.add(etiqueta, gridBagConstraints);

        add(etiquetaInferior, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void tbDImpresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDImpresionActionPerformed
        this.tbDWeb.setSelected(false);
        this.tbBorrador.setSelected(false);
    }//GEN-LAST:event_tbDImpresionActionPerformed

    private void tbDWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDWebActionPerformed
        this.tbDImpresion.setSelected(false);
        this.tbBorrador.setSelected(false);
    }//GEN-LAST:event_tbDWebActionPerformed

    private void tbBorradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbBorradorActionPerformed
        this.tbDImpresion.setSelected(false);
        this.tbDWeb.setSelected(false);
    }//GEN-LAST:event_tbBorradorActionPerformed

    private void tbEsquemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbEsquemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbEsquemaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgVistas;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel etiqueta;
    private javax.swing.JPanel etiquetaInferior;
    private javax.swing.JPanel pBotonesGrandes;
    private javax.swing.JPanel pBotonesPequennos;
    private javax.swing.JToggleButton tbBorrador;
    private javax.swing.JToggleButton tbDImpresion;
    private javax.swing.JToggleButton tbDWeb;
    private javax.swing.JToggleButton tbEsquema;
    private javax.swing.JToggleButton tbMLectura;
    // End of variables declaration//GEN-END:variables
}
