/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.alfsamser.Plantillas;

/**
 *
 * @author Samu
 */
public class PanelVistas extends javax.swing.JPanel {

    /**
     * Creates new form Plantilla
     */
    public PanelVistas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contenido = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bLectura = new javax.swing.JButton();
        tbDImpresion = new javax.swing.JToggleButton();
        tbDWeb = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        tbEsquema = new javax.swing.JToggleButton();
        tbBorrador = new javax.swing.JToggleButton();
        etiquetaInferior = new javax.swing.JPanel();
        etiqueta = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        contenido.setBackground(new java.awt.Color(243, 243, 243));
        contenido.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(243, 243, 243));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        bLectura.setBackground(new java.awt.Color(243, 243, 243));
        bLectura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vista/LeerMas.png"))); // NOI18N
        bLectura.setText("<html><p1 align=\"center\"><p>Modo</p><p>Lectura</p></p1></html>");
        bLectura.setBorder(null);
        bLectura.setBorderPainted(false);
        bLectura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bLectura.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bLectura.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(bLectura);

        tbDImpresion.setBackground(new java.awt.Color(243, 243, 243));
        tbDImpresion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vista/DiseñoImpresion.png"))); // NOI18N
        tbDImpresion.setText("<html><p1 align=\"center\"><p>Diseño de</p><p>impresión</p></p1></html>");
        tbDImpresion.setBorder(null);
        tbDImpresion.setBorderPainted(false);
        tbDImpresion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbDImpresion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tbDImpresion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(tbDImpresion);

        tbDWeb.setBackground(new java.awt.Color(243, 243, 243));
        tbDWeb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vista/DiseñoWeb.png"))); // NOI18N
        tbDWeb.setText("<html><p1 align=\"center\"><p>Diseño</p><p>web</p></p1></html>");
        tbDWeb.setBorder(null);
        tbDWeb.setBorderPainted(false);
        tbDWeb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbDWeb.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tbDWeb.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(tbDWeb);

        contenido.add(jPanel1, new java.awt.GridBagConstraints());

        jPanel2.setBackground(new java.awt.Color(243, 243, 243));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        tbEsquema.setBackground(new java.awt.Color(243, 243, 243));
        tbEsquema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vista/esquema (1).png"))); // NOI18N
        tbEsquema.setText("Esquema");
        tbEsquema.setBorder(null);
        tbEsquema.setBorderPainted(false);
        jPanel2.add(tbEsquema);

        tbBorrador.setBackground(new java.awt.Color(243, 243, 243));
        tbBorrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vista/borrador (1).png"))); // NOI18N
        tbBorrador.setText("Borrador");
        tbBorrador.setBorder(null);
        tbBorrador.setBorderPainted(false);
        jPanel2.add(tbBorrador);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        contenido.add(jPanel2, gridBagConstraints);

        add(contenido, java.awt.BorderLayout.CENTER);

        etiquetaInferior.setLayout(new java.awt.GridBagLayout());

        etiqueta.setForeground(new java.awt.Color(112, 108, 108));
        etiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta.setText("Vistas");
        etiqueta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        etiqueta.setFocusable(false);
        etiqueta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        etiqueta.setPreferredSize(new java.awt.Dimension(200, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BELOW_BASELINE;
        gridBagConstraints.weightx = 1.0;
        etiquetaInferior.add(etiqueta, gridBagConstraints);

        add(etiquetaInferior, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLectura;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel etiqueta;
    private javax.swing.JPanel etiquetaInferior;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton tbBorrador;
    private javax.swing.JToggleButton tbDImpresion;
    private javax.swing.JToggleButton tbDWeb;
    private javax.swing.JToggleButton tbEsquema;
    // End of variables declaration//GEN-END:variables
}
