/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.alfsamser.Paneles.Vista;

import es.alfsamser.Paneles.*;

/**
 *
 * @author Alfre
 */
public class PlanelZoom extends javax.swing.JPanel {

    /**
     * Creates new form Plantilla
     */
    public PlanelZoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contenido = new javax.swing.JPanel();
        bZoom = new javax.swing.JButton();
        cbZoom = new javax.swing.JComboBox<>();
        bCien = new javax.swing.JButton();
        lPorcentage = new javax.swing.JLabel();
        bUnaPagina = new javax.swing.JButton();
        bDoblePagina = new javax.swing.JButton();
        bLateralPagina = new javax.swing.JButton();
        etiqueta = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        contenido.setLayout(new java.awt.GridBagLayout());

        bZoom.setBackground(new java.awt.Color(241, 241, 241));
        bZoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vista/Lupa.png"))); // NOI18N
        bZoom.setText("Zoom");
        bZoom.setBorder(null);
        bZoom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bZoom.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bZoom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        contenido.add(bZoom, gridBagConstraints);

        cbZoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100%" }));
        cbZoom.setMinimumSize(new java.awt.Dimension(60, 22));
        cbZoom.setPreferredSize(new java.awt.Dimension(62, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        contenido.add(cbZoom, gridBagConstraints);

        bCien.setBackground(new java.awt.Color(241, 241, 241));
        bCien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vista/100.png"))); // NOI18N
        bCien.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        contenido.add(bCien, gridBagConstraints);

        lPorcentage.setText("100%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        contenido.add(lPorcentage, gridBagConstraints);

        bUnaPagina.setBackground(new java.awt.Color(241, 241, 241));
        bUnaPagina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Parrafo/justificar.png"))); // NOI18N
        bUnaPagina.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        contenido.add(bUnaPagina, gridBagConstraints);

        bDoblePagina.setBackground(new java.awt.Color(241, 241, 241));
        bDoblePagina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Parrafo/justificar.png"))); // NOI18N
        bDoblePagina.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        contenido.add(bDoblePagina, gridBagConstraints);

        bLateralPagina.setBackground(new java.awt.Color(241, 241, 241));
        bLateralPagina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Parrafo/justificar.png"))); // NOI18N
        bLateralPagina.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        contenido.add(bLateralPagina, gridBagConstraints);

        add(contenido, java.awt.BorderLayout.CENTER);

        etiqueta.setForeground(new java.awt.Color(112, 108, 108));
        etiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta.setText("Etiqueta");
        etiqueta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        etiqueta.setFocusable(false);
        etiqueta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        etiqueta.setPreferredSize(new java.awt.Dimension(200, 15));
        add(etiqueta, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCien;
    private javax.swing.JButton bDoblePagina;
    private javax.swing.JButton bLateralPagina;
    private javax.swing.JButton bUnaPagina;
    private javax.swing.JButton bZoom;
    private javax.swing.JComboBox<String> cbZoom;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel etiqueta;
    private javax.swing.JLabel lPorcentage;
    // End of variables declaration//GEN-END:variables
}
